openapi: 3.0.3
info:
  title: Technical test Jose Gabriel Perea Medina - OpenAPI 3.0
  description: Technical test Jose Gabriel Perea Medina
  termsOfService: http://swagger.io/terms/
  contact:
    email: joegpermed@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
paths:
  /prices:
    post:
      summary: Query Prices for test technisian
      description: Query Prices for test technisian
      operationId: finalPrice
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Output'
        '400':
          description: Invalid ID supplied
        '404':
          description: This query not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Validation exception
components:
  schemas:
    Input:
      required:
        - fechaDeAplicacion
        - identificadorDeProducto
        - identificadorDeCadena
      type: object
      properties:
        fechaDeAplicacion:
          type: string
          pattern: ^\d{4}-\d{2}-\d{2}-\d{2}.\d{2}.\d{2}$
          example: '2020-12-31-23.59.59'
        identificadorDeProducto:
          type: number
          format: int
          example: 35455
        identificadorDeCadena:
          type: number
          format: int
          example: 1
    Output:
      type: object
      properties:
        identificadorDeProducto:
          type: number
          example: 35455
        identificadorDeCadena:
          type: number
          example: 1
        tarifaAplicar:
          type: string
          format: decimal
          example: 100.00
        fechasDeAplicacion:
          type: array
          items:
            type: string
            example: ['2020-12-31-23.59.59']
        precioFinalAplicar:
          type: number
          format: decimal
          example: 100.00
    Error:
      type: object
      properties:
        message:
          type: string
          example: 'message de error'